language: node_js
node_js:
  - "18"
  - "20"
  - "22"

cache: npm

install:
  - npm ci

script:
  - npm run lint
  - npm test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: "20"

branches:
  only:
    - main
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email: false